name: Runner test

on: push

jobs:
  image:
    name: Build image
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Do build
        run: PATH=$HOME/.local/bin:$PATH sh build.sh